---
- name: Adjust IPTables NAT for ECS [Prerouting]
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 169.254.170.2
    destination_port: 80
    jump: DNAT
    to_destination: 127.0.0.1:51679
  tags: iptables

- name: Adjust IPTables NAT for ECS [Output]
  iptables:
    table: nat
    chain: OUTPUT
    protocol: tcp
    destination: 169.254.170.2
    destination_port: 80
    jump: REDIRECT
    to_ports: 51679
  tags: iptables

- name: Save IPTables configuration
  shell: "iptables-save > /etc/sysconfig/iptables"
  tags: iptables