---
- name: IPTables Flush
  iptables:
    chain: '{{ item }}'
    flush: yes
  with_items:
    - FORWARD
    - INPUT
    - OUTPUT
  notify: IPTables Save

- name: IPTables Save
  shell: "iptables-save > /etc/sysconfig/iptables"